//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookHeaven.Reader.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BookHeaven.Reader.Resources.Localization.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All.
        /// </summary>
        public static string ALL_M {
            get {
                return ResourceManager.GetString("ALL_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apps.
        /// </summary>
        public static string APPS {
            get {
                return ResourceManager.GetString("APPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Books.
        /// </summary>
        public static string BOOKS {
            get {
                return ResourceManager.GetString("BOOKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No books matching the current filter.
        /// </summary>
        public static string BOOKS_NO_FILTER_MATCH {
            get {
                return ResourceManager.GetString("BOOKS_NO_FILTER_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a By Author.
        /// </summary>
        public static string BY_AUTHOR {
            get {
                return ResourceManager.GetString("BY_AUTHOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Missing.
        /// </summary>
        public static string BY_MISSING {
            get {
                return ResourceManager.GetString("BY_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please check the URL and try again.
        /// </summary>
        public static string CHECK_THE_URL {
            get {
                return ResourceManager.GetString("CHECK_THE_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Connection established.
        /// </summary>
        public static string CONNECTION_ESTABLISHED {
            get {
                return ResourceManager.GetString("CONNECTION_ESTABLISHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Connection failed.
        /// </summary>
        public static string Connection_failed {
            get {
                return ResourceManager.GetString("Connection_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continue.
        /// </summary>
        public static string CONTINUE {
            get {
                return ResourceManager.GetString("CONTINUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Download.
        /// </summary>
        public static string DOWNLOAD {
            get {
                return ResourceManager.GetString("DOWNLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Downloading....
        /// </summary>
        public static string DOWNLOADING {
            get {
                return ResourceManager.GetString("DOWNLOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please, enter your server&apos;s URL.
        /// </summary>
        public static string ENTER_SERVER_URL {
            get {
                return ResourceManager.GetString("ENTER_SERVER_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Only HTTPS protocol is supported.
        /// </summary>
        public static string HTTPS_ONLY {
            get {
                return ResourceManager.GetString("HTTPS_ONLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Info.
        /// </summary>
        public static string INFO {
            get {
                return ResourceManager.GetString("INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Initializing.
        /// </summary>
        public static string INITIALIZING {
            get {
                return ResourceManager.GetString("INITIALIZING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a English.
        /// </summary>
        public static string LANG_EN {
            get {
                return ResourceManager.GetString("LANG_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spanish.
        /// </summary>
        public static string LANG_ES {
            get {
                return ResourceManager.GetString("LANG_ES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Loading....
        /// </summary>
        public static string LOADING {
            get {
                return ResourceManager.GetString("LOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Loading your book....
        /// </summary>
        public static string LOADING_BOOK {
            get {
                return ResourceManager.GetString("LOADING_BOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Local.
        /// </summary>
        public static string LOCAL {
            get {
                return ResourceManager.GetString("LOCAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New.
        /// </summary>
        public static string NEW {
            get {
                return ResourceManager.GetString("NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No books found in your library.
        /// </summary>
        public static string NO_BOOKS_FOUND {
            get {
                return ResourceManager.GetString("NO_BOOKS_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open.
        /// </summary>
        public static string OPEN {
            get {
                return ResourceManager.GetString("OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reading.
        /// </summary>
        public static string READING {
            get {
                return ResourceManager.GetString("READING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remote.
        /// </summary>
        public static string REMOTE {
            get {
                return ResourceManager.GetString("REMOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Retry.
        /// </summary>
        public static string RETRY {
            get {
                return ResourceManager.GetString("RETRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Let&apos;s set things up.
        /// </summary>
        public static string SET_UP {
            get {
                return ResourceManager.GetString("SET_UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings.
        /// </summary>
        public static string SETTINGS {
            get {
                return ResourceManager.GetString("SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sync completed.
        /// </summary>
        public static string SYNC_COMPLETED {
            get {
                return ResourceManager.GetString("SYNC_COMPLETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sync Progress.
        /// </summary>
        public static string SYNC_PROGRESS {
            get {
                return ResourceManager.GetString("SYNC_PROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Uninstall.
        /// </summary>
        public static string UNINSTALL {
            get {
                return ResourceManager.GetString("UNINSTALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome to {0}.
        /// </summary>
        public static string WELCOME {
            get {
                return ResourceManager.GetString("WELCOME", resourceCulture);
            }
        }
    }
}
